//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IComputation")]
public interface IComputation
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComputation/Negate", ReplyAction="http://tempuri.org/IComputation/NegateResponse")]
    double Negate(double x);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComputation/Negate", ReplyAction="http://tempuri.org/IComputation/NegateResponse")]
    System.Threading.Tasks.Task<double> NegateAsync(double x);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComputation/StringToNumber", ReplyAction="http://tempuri.org/IComputation/StringToNumberResponse")]
    double StringToNumber(string text);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComputation/StringToNumber", ReplyAction="http://tempuri.org/IComputation/StringToNumberResponse")]
    System.Threading.Tasks.Task<double> StringToNumberAsync(string text);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IComputationChannel : IComputation, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ComputationClient : System.ServiceModel.ClientBase<IComputation>, IComputation
{
    
    public ComputationClient()
    {
    }
    
    public ComputationClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ComputationClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ComputationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ComputationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double Negate(double x)
    {
        return base.Channel.Negate(x);
    }
    
    public System.Threading.Tasks.Task<double> NegateAsync(double x)
    {
        return base.Channel.NegateAsync(x);
    }
    
    public double StringToNumber(string text)
    {
        return base.Channel.StringToNumber(text);
    }
    
    public System.Threading.Tasks.Task<double> StringToNumberAsync(string text)
    {
        return base.Channel.StringToNumberAsync(text);
    }
}
