//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRemoteOperations")]
public interface IRemoteOperations
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteOperations/SaveScreenshot", ReplyAction="http://tempuri.org/IRemoteOperations/SaveScreenshotResponse")]
    void SaveScreenshot(string filepath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteOperations/SaveScreenshot", ReplyAction="http://tempuri.org/IRemoteOperations/SaveScreenshotResponse")]
    System.Threading.Tasks.Task SaveScreenshotAsync(string filepath);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRemoteOperationsChannel : IRemoteOperations, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RemoteOperationsClient : System.ServiceModel.ClientBase<IRemoteOperations>, IRemoteOperations
{
    
    public RemoteOperationsClient()
    {
    }
    
    public RemoteOperationsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RemoteOperationsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RemoteOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RemoteOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SaveScreenshot(string filepath)
    {
        base.Channel.SaveScreenshot(filepath);
    }
    
    public System.Threading.Tasks.Task SaveScreenshotAsync(string filepath)
    {
        return base.Channel.SaveScreenshotAsync(filepath);
    }
}
